"Generic settigns
syntax on
filetype plugin indent on
set number
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab
set colorcolumn=120
set autoindent
set smartindent
set autoread
set listchars=tab:▸\ ,trail:▫
set incsearch
set hlsearch
set ignorecase
set smartcase
set history=200
set showcmd
highlight ColorColumn ctermbg=lightgray
set mouse=a

"Set runtime path and vimrc path
let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"
"Also set the current project path as default
set path =.,**

"Set other variables
let $COLORS="/usr/share/vim/vim82/syntax/hitest.vim"

"GUI Settings
if has('gui_running')
	colorscheme slate
	set guifont=Hack\ 11
	map <C-Tab> gt
	map <C-S-Tab> gT
else
	source ~/.vim/plugins/statusline.vim
endif

"Added packages
"added
packadd termdebug

"Bindings
	"Normal mode
nnoremap zo o<esc>
nnoremap zO O<esc>
nmap z<down> zok
nmap z<up> zOj
nnoremap <left> :bprev<cr>
nnoremap <right> :bnext<cr>


		"F keys
nnoremap <F1> :w<cr> :make<cr>
nnoremap <F4> :! ./gmake.sh<cr>
nnoremap <F5> :! clear ; ./x*<cr>
nnoremap <F6> :cprevious<cr>
nnoremap <F7> :cnext<cr>
nnoremap <F8> :Termdebug<cr>
nnoremap <F9> :mksession! Vim/current.vim<cr>
nnoremap <F10> :source Vim/current.vim<cr>
nnoremap <F11> :! ~/Coding/Bash/Random_Script/vimPull.sh<cr>
nnoremap <F12> :! ~/Coding/Bash/Random_Script/vimPush.sh<cr>
	"Insert mode
imap <F6> <ESC>:cprevious<cr>a
imap <F7> <ESC>:cnext<cr>a
	"Visual mode
	"Selcet	mode
	"CmdLin	mode
	"PendOp mode

